disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace

line_length: 400
type_name:
min_length: 4 # only warning
max_length: # warning and error
warning: 50
error: 100
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
nesting:
    type_level: 5
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - R.generated.swift
